spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  application:
    name: BangFer

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    doc-expansion : none